server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${KEYSECRET_SECURITY}
  expiration: ${EXPIRE_DAYS_SECURITY}

user-microservice:
  url: ${URL_USER_MICROSERVICE}

messenger-microservice:
  url: ${URL_MESSENGER_MICROSERVICE}

traceability-microservice:
  url: ${URL_TRACEABILITY_MICROSERVICE}
